name: 'MacOS Build'
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Debug Environment
        run: |
          pwd
          ls -la
          node --version
          npm --version
          rustc --version
      
      - name: Install frontend dependencies
        run: |
          npm install
          npm list --depth=0
      
      - name: Debug Build Directory
        run: |
          pwd
          ls -la
          
      - name: Build Frontend
        run: |
          npm run build
          echo "Build completed, checking build directory:"
          ls -la build
      
      - name: Build Tauri
        run: |
          cd src-tauri
          cargo build --verbose
          cd ..
          npm run tauri build -- --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}