name: 'MacOS Build Debug'
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      
      - name: Install SQLite
        run: |
          brew install sqlite
          
      - name: Install Dependencies
        run: |
          echo "Installing npm dependencies..."
          npm install
          echo "\nVerifying sqlite installation:"
          sqlite3 --version
          
      - name: Build Frontend
        run: |
          echo "Starting frontend build..."
          npm run build
          echo "\nBuild directory contents:"
          ls -la build || echo "build directory not found"
          
      - name: Install Rust Dependencies
        run: |
          cd src-tauri
          echo "Updating Rust dependencies..."
          cargo update
          echo "Running cargo check..."
          cargo check --verbose
          cd ..
          
      - name: Build Tauri
        run: |
          echo "Starting Tauri build with verbose output..."
          npm run tauri build -- --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full
          RUSTFLAGS: "-C debuginfo=2"
          
      - name: List Build Artifacts
        if: always()
        run: |
          echo "Checking build artifacts..."
          ls -R src-tauri/target/ || echo "No target directory"
          
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: |
            npm-debug.log*
            src-tauri/target/debug/build/**/output.txt
            src-tauri/target/debug/build/**/stderr.txt
            src-tauri/target/release/build/**/output.txt